"""
generate_gallery.py
Generates index.html for GitHub Pages gallery.
"""
import os
from datetime import datetime

BASE_URL = "https://ellismith.github.io/dissimilarity"

CELL_TYPES = [
    'GABAergic-neurons', 'glutamatergic-neurons', 'astrocytes', 'microglia',
    'basket-cells', 'medium-spiny-neurons', 'cerebellar-neurons', 'ependymal-cells',
    'midbrain-neurons', 'oligodendrocytes', 'vascular-cells',
]

def img_block(url, caption, path=""):
    return f"""
<div class="fig">
  <a href="{url}" target="_blank">
    <img src="{url}" alt="{caption}">
  </a>
  <p class="caption">{caption}</p>
  {"<p class='path'>" + path + "</p>" if path else ""}
</div>
"""

lines = []
lines.append(f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Transcriptional Individuality — Aging Primate Brain</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 1400px; margin: 0 auto; padding: 20px; color: #222; }}
  h1 {{ font-size: 1.6em; font-weight: 500; border-bottom: 1px solid #ddd; padding-bottom: 8px; }}
  h2 {{ font-size: 1.2em; font-weight: 500; margin-top: 2em; border-bottom: 1px solid #eee; padding-bottom: 4px; }}
  nav {{ margin: 1em 0; font-size: 0.9em; }}
  nav a {{ margin-right: 16px; color: #0066cc; text-decoration: none; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(420px, 1fr)); gap: 20px; margin: 1em 0; }}
  .grid-wide {{ display: grid; grid-template-columns: 1fr; gap: 20px; margin: 1em 0; }}
  .fig {{ border: 1px solid #eee; border-radius: 6px; padding: 10px; background: #fafafa; }}
  .fig img {{ width: 100%; height: auto; border-radius: 4px; cursor: zoom-in; }}
  .fig .caption {{ font-size: 0.85em; font-weight: 500; margin: 6px 0 2px; }}
  .fig .path {{ font-size: 0.75em; color: #888; font-family: monospace; margin: 0; }}
  .meta {{ font-size: 0.85em; color: #666; margin-bottom: 1em; }}
  footer {{ margin-top: 3em; font-size: 0.8em; color: #999; border-top: 1px solid #eee; padding-top: 8px; }}
</style>
</head>
<body>
<h1>Transcriptional Individuality — Aging Primate Brain</h1>
<p class="meta">Last updated: {datetime.now().strftime("%Y-%m-%d %H:%M")} &nbsp;|&nbsp; 12 cell types · 11 brain regions · ~55 animals</p>

<nav>
  <a href="#lochness">lochNESS</a>
  <a href="#centroid_scatter">Centroid vs lochNESS</a>
  <a href="#centroid_heatmaps">Centroid Heatmaps</a>
  <a href="#embedding">PCA Embedding QC</a>
</nav>
""")

# lochNESS summary
lines.append('<h2 id="lochness">lochNESS — Continuous Age Neighborhood Clustering</h2>')
lines.append('<p style="font-size:0.9em">For each cell, mean age of k=10 nearest PCA neighbors. Pearson r between cell age and neighbor mean age, tested against permuted null. Positive r = old cells cluster with old cells.</p>')
lines.append('<div class="grid-wide">')
lines.append(img_block(
    f"{BASE_URL}/img/lochness_heatmap_celltype_region.png",
    "lochNESS summary — cell type × region",
    "lochness_heatmap_celltype_region.png"
))
lines.append('</div>')

# centroid vs lochness scatter
lines.append('<h2 id="centroid_scatter">Centroid Distance vs lochNESS</h2>')
lines.append('<p style="font-size:0.9em">Per louvain × region: centroid distance age r vs lochNESS age r. Tests whether the two metrics are correlated or dissociated.</p>')
lines.append('<div class="grid-wide">')
lines.append(img_block(
    f"{BASE_URL}/img/centroid_vs_lochness_scatter.png",
    "centroid distance vs lochNESS age correlations",
    "centroid_vs_lochness_scatter.png"
))
lines.append('</div>')

# centroid heatmaps
lines.append('<h2 id="centroid_heatmaps">Centroid Distance Heatmaps</h2>')
lines.append('<p style="font-size:0.9em">Pearson r (louvain × region) for within-animal and population centroid distance ~ age. Left = within-animal spread, right = population drift.</p>')
lines.append('<div class="grid">')
for ct in CELL_TYPES:
    fname = f"{ct}_centroid_heatmap_mean.png"
    fpath = f"img/centroid_heatmaps/{fname}"
    if os.path.exists(fpath):
        lines.append(img_block(
            f"{BASE_URL}/img/centroid_heatmaps/{fname}",
            f"{ct} — centroid distance ~ age",
            f"centroid_heatmaps/{fname}"
        ))
lines.append('</div>')

# embedding QC
lines.append('<h2 id="embedding">PCA Embedding QC</h2>')
lines.append('<p style="font-size:0.9em">Log10 total cells, n louvains, PC1 std, and mean L2 norm per cell type × region.</p>')
lines.append('<div class="grid-wide">')
lines.append(img_block(
    f"{BASE_URL}/img/pca_embedding_summary.png",
    "PCA embedding summary",
    "pca_embedding_summary.png"
))
lines.append('</div>')

lines.append(f"""
<footer>Generated by generate_gallery.py &nbsp;|&nbsp; easmit31 / dissimilarity</footer>
</body>
</html>
""")

with open('index.html', 'w') as f:
    f.write('\n'.join(lines))
print("saved: index.html")
